# 1. Versi Docker Compose
version: "3.8"

# 2. Service (container2 yang akan kita buat)
services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:27017
    networks: 
      - java_networks

  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks: 
      - java_networks

  java-docker:
    container_name: java-docker
    image: java-docker:1.0
    ports: 
      - 8080:8080
    depends_on: 
      - redis  
      - mongo
    environment: 
      - NAME=Docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks: 
      - java_networks

networks:
  java_networks: 
    name: java_networks